//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caminaconestilo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class camina_con_estiloEntities : DbContext
    {
        public camina_con_estiloEntities()
            : base("name=camina_con_estiloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<compra> compra { get; set; }
        public DbSet<devolucion> devolucion { get; set; }
        public DbSet<entrada_x_ajuste> entrada_x_ajuste { get; set; }
        public DbSet<existencia> existencia { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
