//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caminaconestilo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.devolucion = new HashSet<devolucion>();
            this.entrada_x_ajuste = new HashSet<entrada_x_ajuste>();
            this.existencia = new HashSet<existencia>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<devolucion> devolucion { get; set; }
        public virtual ICollection<entrada_x_ajuste> entrada_x_ajuste { get; set; }
        public virtual ICollection<existencia> existencia { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
